"dataset":
  "name": "adult"
  "path": "datasets/adult_sklearn/adult_sklearn.csv"
  "path_train": "datasets/adult_sklearn/adult_sklearn_train.csv"
  "path_test": "datasets/adult_sklearn/adult_sklearn_test.csv"
  "target": "income"
  "sensitive": "sex"
  "privileged": ["Male"]
  "unprivileged": ["Female"]
  "favorable": ">50K"
  "unfavorable": "<=50K"
"model":
  "name": "neural_network"
  "params": {}
"mitigation":
  "pre":
    "name": "lfr"
    "params": {
      "k": 5,
      "Ax": 0.01,   # reconstrucao X
      "Ay": 5.0,    # preservar Y
      "Az": 20.0,   # fairness
      "print_interval": 250,
      "maxiter": 5000,
      "maxfun": 5000,
      "threshold": 0.3,
      "verbose": 1,
      "seed": 42}
  "in":
    "name": "none"
    "params": {}
  "post":
    "name": "none"
    "params": {}
