"dataset":
  "name": "adult"
  "path": "datasets/adult_sklearn/adult_sklearn.csv"
  "path_train": "datasets/adult_sklearn/adult_sklearn_train.csv"
  "path_val": "datasets/adult_sklearn/adult_sklearn_val.csv"
  "path_test": "datasets/adult_sklearn/adult_sklearn_test.csv"
  "cols_exclude": ["fnlwgt"]
  "cols_cat": ["workclass", "education", "marital-status", "occupation", "relationship",
    "race", "native-country"]
  "target": "income"
  "sensitive": "sex"
  "privileged": ["Male"]
  "unprivileged": ["Female"]
  "favorable": ">50K"
  "unfavorable": "<=50K"
"model":
  "name": "random_forest"
  "params":
    "bootstrap": true
    "ccp_alpha": 0.0
    "criterion": "gini"
    "max_bins": 256
    "max_features": "sqrt"
    "min_bin_size": 1
    "min_impurity_decrease": 0.0
    "min_samples_leaf": 20
    "min_samples_split": 2
    "min_weight_fraction_leaf": 0.0
    "n_estimators": 100
    "oob_score": false
"mitigation":
  "pre":
    "name": "disparate_impact_remover"
    "params":
      "repair_level": 1.0
  "in":
    "name": "none"
    "params": {}
  "post":
    "name": "equalized_odds_postprocessing"
    "params": {}
