dataset:
  name: "adult"
  path: "datasets/adult_sklearn/adult_sklearn.csv"
  target: "income"
  sensitive: "sex"
  privileged: ["Male"]        #1
  unprivileged: ["Female"]    #0
  favorable: ">50K"           #1
  unfavorable: "<=50K"        #0

split:
  test_size: 0.2
  random_state: 50

model:
  name: "decision_tree"
  params:
    criterion: "gini"
    max_depth: 6
    min_samples_split: 2
    min_samples_leaf: 1

mitigation:
  pre:
    name: "reweighing"
    params: {}
  in:
    name: "none" #"adversarialdebiasing"
    params: {}
  post:
    name: "none"
    params: {}
